// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PropInfoData.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace message {

void protobuf_ShutdownFile_PropInfoData_2eproto() {
  delete PropInfoData::default_instance_;
}

void protobuf_AddDesc_PropInfoData_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::message::protobuf_AddDesc_PropInfo_2eproto();
  PropInfoData::default_instance_ = new PropInfoData();
  PropInfoData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PropInfoData_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PropInfoData_2eproto {
  StaticDescriptorInitializer_PropInfoData_2eproto() {
    protobuf_AddDesc_PropInfoData_2eproto();
  }
} static_descriptor_initializer_PropInfoData_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int PropInfoData::kManualPropInfoListFieldNumber;
const int PropInfoData::kBufferPropInfoListFieldNumber;
const int PropInfoData::kGiftBagPropInfoListFieldNumber;
const int PropInfoData::kCheapPropInfoListFieldNumber;
const int PropInfoData::kLockPropInfoListFieldNumber;
#endif  // !_MSC_VER

PropInfoData::PropInfoData()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void PropInfoData::InitAsDefaultInstance() {
}

PropInfoData::PropInfoData(const PropInfoData& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void PropInfoData::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PropInfoData::~PropInfoData() {
  SharedDtor();
}

void PropInfoData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PropInfoData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PropInfoData& PropInfoData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PropInfoData_2eproto();  return *default_instance_;
}

PropInfoData* PropInfoData::default_instance_ = NULL;

PropInfoData* PropInfoData::New() const {
  return new PropInfoData;
}

void PropInfoData::Clear() {
  manualpropinfolist_.Clear();
  bufferpropinfolist_.Clear();
  giftbagpropinfolist_.Clear();
  cheappropinfolist_.Clear();
  lockpropinfolist_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool PropInfoData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .message.PropInfo manualPropInfoList = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_manualPropInfoList:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_manualpropinfolist()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_manualPropInfoList;
        if (input->ExpectTag(18)) goto parse_bufferPropInfoList;
        break;
      }
      
      // repeated .message.PropInfo bufferPropInfoList = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_bufferPropInfoList:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_bufferpropinfolist()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_bufferPropInfoList;
        if (input->ExpectTag(26)) goto parse_giftBagPropInfoList;
        break;
      }
      
      // repeated .message.PropInfo giftBagPropInfoList = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_giftBagPropInfoList:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_giftbagpropinfolist()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_giftBagPropInfoList;
        if (input->ExpectTag(34)) goto parse_cheapPropInfoList;
        break;
      }
      
      // repeated .message.PropInfo cheapPropInfoList = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_cheapPropInfoList:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_cheappropinfolist()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_cheapPropInfoList;
        if (input->ExpectTag(42)) goto parse_lockPropInfoList;
        break;
      }
      
      // repeated .message.PropInfo lockPropInfoList = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_lockPropInfoList:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_lockpropinfolist()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_lockPropInfoList;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PropInfoData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .message.PropInfo manualPropInfoList = 1;
  for (int i = 0; i < this->manualpropinfolist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->manualpropinfolist(i), output);
  }
  
  // repeated .message.PropInfo bufferPropInfoList = 2;
  for (int i = 0; i < this->bufferpropinfolist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->bufferpropinfolist(i), output);
  }
  
  // repeated .message.PropInfo giftBagPropInfoList = 3;
  for (int i = 0; i < this->giftbagpropinfolist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->giftbagpropinfolist(i), output);
  }
  
  // repeated .message.PropInfo cheapPropInfoList = 4;
  for (int i = 0; i < this->cheappropinfolist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->cheappropinfolist(i), output);
  }
  
  // repeated .message.PropInfo lockPropInfoList = 5;
  for (int i = 0; i < this->lockpropinfolist_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5, this->lockpropinfolist(i), output);
  }
  
}

int PropInfoData::ByteSize() const {
  int total_size = 0;
  
  // repeated .message.PropInfo manualPropInfoList = 1;
  total_size += 1 * this->manualpropinfolist_size();
  for (int i = 0; i < this->manualpropinfolist_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->manualpropinfolist(i));
  }
  
  // repeated .message.PropInfo bufferPropInfoList = 2;
  total_size += 1 * this->bufferpropinfolist_size();
  for (int i = 0; i < this->bufferpropinfolist_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->bufferpropinfolist(i));
  }
  
  // repeated .message.PropInfo giftBagPropInfoList = 3;
  total_size += 1 * this->giftbagpropinfolist_size();
  for (int i = 0; i < this->giftbagpropinfolist_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->giftbagpropinfolist(i));
  }
  
  // repeated .message.PropInfo cheapPropInfoList = 4;
  total_size += 1 * this->cheappropinfolist_size();
  for (int i = 0; i < this->cheappropinfolist_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->cheappropinfolist(i));
  }
  
  // repeated .message.PropInfo lockPropInfoList = 5;
  total_size += 1 * this->lockpropinfolist_size();
  for (int i = 0; i < this->lockpropinfolist_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->lockpropinfolist(i));
  }
  
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PropInfoData::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PropInfoData*>(&from));
}

void PropInfoData::MergeFrom(const PropInfoData& from) {
  GOOGLE_CHECK_NE(&from, this);
  manualpropinfolist_.MergeFrom(from.manualpropinfolist_);
  bufferpropinfolist_.MergeFrom(from.bufferpropinfolist_);
  giftbagpropinfolist_.MergeFrom(from.giftbagpropinfolist_);
  cheappropinfolist_.MergeFrom(from.cheappropinfolist_);
  lockpropinfolist_.MergeFrom(from.lockpropinfolist_);
}

void PropInfoData::CopyFrom(const PropInfoData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PropInfoData::IsInitialized() const {
  
  for (int i = 0; i < manualpropinfolist_size(); i++) {
    if (!this->manualpropinfolist(i).IsInitialized()) return false;
  }
  for (int i = 0; i < bufferpropinfolist_size(); i++) {
    if (!this->bufferpropinfolist(i).IsInitialized()) return false;
  }
  for (int i = 0; i < giftbagpropinfolist_size(); i++) {
    if (!this->giftbagpropinfolist(i).IsInitialized()) return false;
  }
  for (int i = 0; i < cheappropinfolist_size(); i++) {
    if (!this->cheappropinfolist(i).IsInitialized()) return false;
  }
  for (int i = 0; i < lockpropinfolist_size(); i++) {
    if (!this->lockpropinfolist(i).IsInitialized()) return false;
  }
  return true;
}

void PropInfoData::Swap(PropInfoData* other) {
  if (other != this) {
    manualpropinfolist_.Swap(&other->manualpropinfolist_);
    bufferpropinfolist_.Swap(&other->bufferpropinfolist_);
    giftbagpropinfolist_.Swap(&other->giftbagpropinfolist_);
    cheappropinfolist_.Swap(&other->cheappropinfolist_);
    lockpropinfolist_.Swap(&other->lockpropinfolist_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string PropInfoData::GetTypeName() const {
  return "message.PropInfoData";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)
