// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PropInfoData.proto

package message;

public final class S3PropInfoData {
  private S3PropInfoData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PropInfoDataOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .message.PropInfo manualPropInfoList = 1;
    java.util.List<message.S3PropInfo.PropInfo> 
        getManualPropInfoListList();
    message.S3PropInfo.PropInfo getManualPropInfoList(int index);
    int getManualPropInfoListCount();
    
    // repeated .message.PropInfo bufferPropInfoList = 2;
    java.util.List<message.S3PropInfo.PropInfo> 
        getBufferPropInfoListList();
    message.S3PropInfo.PropInfo getBufferPropInfoList(int index);
    int getBufferPropInfoListCount();
    
    // repeated .message.PropInfo effectPropInfoList = 3;
    java.util.List<message.S3PropInfo.PropInfo> 
        getEffectPropInfoListList();
    message.S3PropInfo.PropInfo getEffectPropInfoList(int index);
    int getEffectPropInfoListCount();
    
    // repeated .message.PropInfo lockPropInfoList = 4;
    java.util.List<message.S3PropInfo.PropInfo> 
        getLockPropInfoListList();
    message.S3PropInfo.PropInfo getLockPropInfoList(int index);
    int getLockPropInfoListCount();
    
    // repeated .message.BuyGold buyGoldList = 5;
    java.util.List<message.S3BuyGold.BuyGold> 
        getBuyGoldListList();
    message.S3BuyGold.BuyGold getBuyGoldList(int index);
    int getBuyGoldListCount();
    
    // repeated .message.PropInfo headList = 6;
    java.util.List<message.S3PropInfo.PropInfo> 
        getHeadListList();
    message.S3PropInfo.PropInfo getHeadList(int index);
    int getHeadListCount();
  }
  public static final class PropInfoData extends
      com.google.protobuf.GeneratedMessageLite
      implements PropInfoDataOrBuilder {
    // Use PropInfoData.newBuilder() to construct.
    private PropInfoData(Builder builder) {
      super(builder);
    }
    private PropInfoData(boolean noInit) {}
    
    private static final PropInfoData defaultInstance;
    public static PropInfoData getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropInfoData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .message.PropInfo manualPropInfoList = 1;
    public static final int MANUALPROPINFOLIST_FIELD_NUMBER = 1;
    private java.util.List<message.S3PropInfo.PropInfo> manualPropInfoList_;
    public java.util.List<message.S3PropInfo.PropInfo> getManualPropInfoListList() {
      return manualPropInfoList_;
    }
    public java.util.List<? extends message.S3PropInfo.PropInfoOrBuilder> 
        getManualPropInfoListOrBuilderList() {
      return manualPropInfoList_;
    }
    public int getManualPropInfoListCount() {
      return manualPropInfoList_.size();
    }
    public message.S3PropInfo.PropInfo getManualPropInfoList(int index) {
      return manualPropInfoList_.get(index);
    }
    public message.S3PropInfo.PropInfoOrBuilder getManualPropInfoListOrBuilder(
        int index) {
      return manualPropInfoList_.get(index);
    }
    
    // repeated .message.PropInfo bufferPropInfoList = 2;
    public static final int BUFFERPROPINFOLIST_FIELD_NUMBER = 2;
    private java.util.List<message.S3PropInfo.PropInfo> bufferPropInfoList_;
    public java.util.List<message.S3PropInfo.PropInfo> getBufferPropInfoListList() {
      return bufferPropInfoList_;
    }
    public java.util.List<? extends message.S3PropInfo.PropInfoOrBuilder> 
        getBufferPropInfoListOrBuilderList() {
      return bufferPropInfoList_;
    }
    public int getBufferPropInfoListCount() {
      return bufferPropInfoList_.size();
    }
    public message.S3PropInfo.PropInfo getBufferPropInfoList(int index) {
      return bufferPropInfoList_.get(index);
    }
    public message.S3PropInfo.PropInfoOrBuilder getBufferPropInfoListOrBuilder(
        int index) {
      return bufferPropInfoList_.get(index);
    }
    
    // repeated .message.PropInfo effectPropInfoList = 3;
    public static final int EFFECTPROPINFOLIST_FIELD_NUMBER = 3;
    private java.util.List<message.S3PropInfo.PropInfo> effectPropInfoList_;
    public java.util.List<message.S3PropInfo.PropInfo> getEffectPropInfoListList() {
      return effectPropInfoList_;
    }
    public java.util.List<? extends message.S3PropInfo.PropInfoOrBuilder> 
        getEffectPropInfoListOrBuilderList() {
      return effectPropInfoList_;
    }
    public int getEffectPropInfoListCount() {
      return effectPropInfoList_.size();
    }
    public message.S3PropInfo.PropInfo getEffectPropInfoList(int index) {
      return effectPropInfoList_.get(index);
    }
    public message.S3PropInfo.PropInfoOrBuilder getEffectPropInfoListOrBuilder(
        int index) {
      return effectPropInfoList_.get(index);
    }
    
    // repeated .message.PropInfo lockPropInfoList = 4;
    public static final int LOCKPROPINFOLIST_FIELD_NUMBER = 4;
    private java.util.List<message.S3PropInfo.PropInfo> lockPropInfoList_;
    public java.util.List<message.S3PropInfo.PropInfo> getLockPropInfoListList() {
      return lockPropInfoList_;
    }
    public java.util.List<? extends message.S3PropInfo.PropInfoOrBuilder> 
        getLockPropInfoListOrBuilderList() {
      return lockPropInfoList_;
    }
    public int getLockPropInfoListCount() {
      return lockPropInfoList_.size();
    }
    public message.S3PropInfo.PropInfo getLockPropInfoList(int index) {
      return lockPropInfoList_.get(index);
    }
    public message.S3PropInfo.PropInfoOrBuilder getLockPropInfoListOrBuilder(
        int index) {
      return lockPropInfoList_.get(index);
    }
    
    // repeated .message.BuyGold buyGoldList = 5;
    public static final int BUYGOLDLIST_FIELD_NUMBER = 5;
    private java.util.List<message.S3BuyGold.BuyGold> buyGoldList_;
    public java.util.List<message.S3BuyGold.BuyGold> getBuyGoldListList() {
      return buyGoldList_;
    }
    public java.util.List<? extends message.S3BuyGold.BuyGoldOrBuilder> 
        getBuyGoldListOrBuilderList() {
      return buyGoldList_;
    }
    public int getBuyGoldListCount() {
      return buyGoldList_.size();
    }
    public message.S3BuyGold.BuyGold getBuyGoldList(int index) {
      return buyGoldList_.get(index);
    }
    public message.S3BuyGold.BuyGoldOrBuilder getBuyGoldListOrBuilder(
        int index) {
      return buyGoldList_.get(index);
    }
    
    // repeated .message.PropInfo headList = 6;
    public static final int HEADLIST_FIELD_NUMBER = 6;
    private java.util.List<message.S3PropInfo.PropInfo> headList_;
    public java.util.List<message.S3PropInfo.PropInfo> getHeadListList() {
      return headList_;
    }
    public java.util.List<? extends message.S3PropInfo.PropInfoOrBuilder> 
        getHeadListOrBuilderList() {
      return headList_;
    }
    public int getHeadListCount() {
      return headList_.size();
    }
    public message.S3PropInfo.PropInfo getHeadList(int index) {
      return headList_.get(index);
    }
    public message.S3PropInfo.PropInfoOrBuilder getHeadListOrBuilder(
        int index) {
      return headList_.get(index);
    }
    
    private void initFields() {
      manualPropInfoList_ = java.util.Collections.emptyList();
      bufferPropInfoList_ = java.util.Collections.emptyList();
      effectPropInfoList_ = java.util.Collections.emptyList();
      lockPropInfoList_ = java.util.Collections.emptyList();
      buyGoldList_ = java.util.Collections.emptyList();
      headList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < manualPropInfoList_.size(); i++) {
        output.writeMessage(1, manualPropInfoList_.get(i));
      }
      for (int i = 0; i < bufferPropInfoList_.size(); i++) {
        output.writeMessage(2, bufferPropInfoList_.get(i));
      }
      for (int i = 0; i < effectPropInfoList_.size(); i++) {
        output.writeMessage(3, effectPropInfoList_.get(i));
      }
      for (int i = 0; i < lockPropInfoList_.size(); i++) {
        output.writeMessage(4, lockPropInfoList_.get(i));
      }
      for (int i = 0; i < buyGoldList_.size(); i++) {
        output.writeMessage(5, buyGoldList_.get(i));
      }
      for (int i = 0; i < headList_.size(); i++) {
        output.writeMessage(6, headList_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < manualPropInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, manualPropInfoList_.get(i));
      }
      for (int i = 0; i < bufferPropInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bufferPropInfoList_.get(i));
      }
      for (int i = 0; i < effectPropInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, effectPropInfoList_.get(i));
      }
      for (int i = 0; i < lockPropInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, lockPropInfoList_.get(i));
      }
      for (int i = 0; i < buyGoldList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, buyGoldList_.get(i));
      }
      for (int i = 0; i < headList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, headList_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static message.S3PropInfoData.PropInfoData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static message.S3PropInfoData.PropInfoData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static message.S3PropInfoData.PropInfoData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static message.S3PropInfoData.PropInfoData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static message.S3PropInfoData.PropInfoData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static message.S3PropInfoData.PropInfoData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static message.S3PropInfoData.PropInfoData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static message.S3PropInfoData.PropInfoData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static message.S3PropInfoData.PropInfoData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static message.S3PropInfoData.PropInfoData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(message.S3PropInfoData.PropInfoData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          message.S3PropInfoData.PropInfoData, Builder>
        implements message.S3PropInfoData.PropInfoDataOrBuilder {
      // Construct using message.S3PropInfoData.PropInfoData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        manualPropInfoList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        bufferPropInfoList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        effectPropInfoList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        lockPropInfoList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        buyGoldList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        headList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public message.S3PropInfoData.PropInfoData getDefaultInstanceForType() {
        return message.S3PropInfoData.PropInfoData.getDefaultInstance();
      }
      
      public message.S3PropInfoData.PropInfoData build() {
        message.S3PropInfoData.PropInfoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private message.S3PropInfoData.PropInfoData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        message.S3PropInfoData.PropInfoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public message.S3PropInfoData.PropInfoData buildPartial() {
        message.S3PropInfoData.PropInfoData result = new message.S3PropInfoData.PropInfoData(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          manualPropInfoList_ = java.util.Collections.unmodifiableList(manualPropInfoList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.manualPropInfoList_ = manualPropInfoList_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          bufferPropInfoList_ = java.util.Collections.unmodifiableList(bufferPropInfoList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.bufferPropInfoList_ = bufferPropInfoList_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          effectPropInfoList_ = java.util.Collections.unmodifiableList(effectPropInfoList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.effectPropInfoList_ = effectPropInfoList_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          lockPropInfoList_ = java.util.Collections.unmodifiableList(lockPropInfoList_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.lockPropInfoList_ = lockPropInfoList_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          buyGoldList_ = java.util.Collections.unmodifiableList(buyGoldList_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.buyGoldList_ = buyGoldList_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          headList_ = java.util.Collections.unmodifiableList(headList_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.headList_ = headList_;
        return result;
      }
      
      public Builder mergeFrom(message.S3PropInfoData.PropInfoData other) {
        if (other == message.S3PropInfoData.PropInfoData.getDefaultInstance()) return this;
        if (!other.manualPropInfoList_.isEmpty()) {
          if (manualPropInfoList_.isEmpty()) {
            manualPropInfoList_ = other.manualPropInfoList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureManualPropInfoListIsMutable();
            manualPropInfoList_.addAll(other.manualPropInfoList_);
          }
          
        }
        if (!other.bufferPropInfoList_.isEmpty()) {
          if (bufferPropInfoList_.isEmpty()) {
            bufferPropInfoList_ = other.bufferPropInfoList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBufferPropInfoListIsMutable();
            bufferPropInfoList_.addAll(other.bufferPropInfoList_);
          }
          
        }
        if (!other.effectPropInfoList_.isEmpty()) {
          if (effectPropInfoList_.isEmpty()) {
            effectPropInfoList_ = other.effectPropInfoList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureEffectPropInfoListIsMutable();
            effectPropInfoList_.addAll(other.effectPropInfoList_);
          }
          
        }
        if (!other.lockPropInfoList_.isEmpty()) {
          if (lockPropInfoList_.isEmpty()) {
            lockPropInfoList_ = other.lockPropInfoList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLockPropInfoListIsMutable();
            lockPropInfoList_.addAll(other.lockPropInfoList_);
          }
          
        }
        if (!other.buyGoldList_.isEmpty()) {
          if (buyGoldList_.isEmpty()) {
            buyGoldList_ = other.buyGoldList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureBuyGoldListIsMutable();
            buyGoldList_.addAll(other.buyGoldList_);
          }
          
        }
        if (!other.headList_.isEmpty()) {
          if (headList_.isEmpty()) {
            headList_ = other.headList_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureHeadListIsMutable();
            headList_.addAll(other.headList_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              message.S3PropInfo.PropInfo.Builder subBuilder = message.S3PropInfo.PropInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addManualPropInfoList(subBuilder.buildPartial());
              break;
            }
            case 18: {
              message.S3PropInfo.PropInfo.Builder subBuilder = message.S3PropInfo.PropInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBufferPropInfoList(subBuilder.buildPartial());
              break;
            }
            case 26: {
              message.S3PropInfo.PropInfo.Builder subBuilder = message.S3PropInfo.PropInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEffectPropInfoList(subBuilder.buildPartial());
              break;
            }
            case 34: {
              message.S3PropInfo.PropInfo.Builder subBuilder = message.S3PropInfo.PropInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLockPropInfoList(subBuilder.buildPartial());
              break;
            }
            case 42: {
              message.S3BuyGold.BuyGold.Builder subBuilder = message.S3BuyGold.BuyGold.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBuyGoldList(subBuilder.buildPartial());
              break;
            }
            case 50: {
              message.S3PropInfo.PropInfo.Builder subBuilder = message.S3PropInfo.PropInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addHeadList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .message.PropInfo manualPropInfoList = 1;
      private java.util.List<message.S3PropInfo.PropInfo> manualPropInfoList_ =
        java.util.Collections.emptyList();
      private void ensureManualPropInfoListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          manualPropInfoList_ = new java.util.ArrayList<message.S3PropInfo.PropInfo>(manualPropInfoList_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<message.S3PropInfo.PropInfo> getManualPropInfoListList() {
        return java.util.Collections.unmodifiableList(manualPropInfoList_);
      }
      public int getManualPropInfoListCount() {
        return manualPropInfoList_.size();
      }
      public message.S3PropInfo.PropInfo getManualPropInfoList(int index) {
        return manualPropInfoList_.get(index);
      }
      public Builder setManualPropInfoList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureManualPropInfoListIsMutable();
        manualPropInfoList_.set(index, value);
        
        return this;
      }
      public Builder setManualPropInfoList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureManualPropInfoListIsMutable();
        manualPropInfoList_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addManualPropInfoList(message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureManualPropInfoListIsMutable();
        manualPropInfoList_.add(value);
        
        return this;
      }
      public Builder addManualPropInfoList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureManualPropInfoListIsMutable();
        manualPropInfoList_.add(index, value);
        
        return this;
      }
      public Builder addManualPropInfoList(
          message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureManualPropInfoListIsMutable();
        manualPropInfoList_.add(builderForValue.build());
        
        return this;
      }
      public Builder addManualPropInfoList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureManualPropInfoListIsMutable();
        manualPropInfoList_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllManualPropInfoList(
          java.lang.Iterable<? extends message.S3PropInfo.PropInfo> values) {
        ensureManualPropInfoListIsMutable();
        super.addAll(values, manualPropInfoList_);
        
        return this;
      }
      public Builder clearManualPropInfoList() {
        manualPropInfoList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeManualPropInfoList(int index) {
        ensureManualPropInfoListIsMutable();
        manualPropInfoList_.remove(index);
        
        return this;
      }
      
      // repeated .message.PropInfo bufferPropInfoList = 2;
      private java.util.List<message.S3PropInfo.PropInfo> bufferPropInfoList_ =
        java.util.Collections.emptyList();
      private void ensureBufferPropInfoListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          bufferPropInfoList_ = new java.util.ArrayList<message.S3PropInfo.PropInfo>(bufferPropInfoList_);
          bitField0_ |= 0x00000002;
         }
      }
      
      public java.util.List<message.S3PropInfo.PropInfo> getBufferPropInfoListList() {
        return java.util.Collections.unmodifiableList(bufferPropInfoList_);
      }
      public int getBufferPropInfoListCount() {
        return bufferPropInfoList_.size();
      }
      public message.S3PropInfo.PropInfo getBufferPropInfoList(int index) {
        return bufferPropInfoList_.get(index);
      }
      public Builder setBufferPropInfoList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBufferPropInfoListIsMutable();
        bufferPropInfoList_.set(index, value);
        
        return this;
      }
      public Builder setBufferPropInfoList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureBufferPropInfoListIsMutable();
        bufferPropInfoList_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addBufferPropInfoList(message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBufferPropInfoListIsMutable();
        bufferPropInfoList_.add(value);
        
        return this;
      }
      public Builder addBufferPropInfoList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBufferPropInfoListIsMutable();
        bufferPropInfoList_.add(index, value);
        
        return this;
      }
      public Builder addBufferPropInfoList(
          message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureBufferPropInfoListIsMutable();
        bufferPropInfoList_.add(builderForValue.build());
        
        return this;
      }
      public Builder addBufferPropInfoList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureBufferPropInfoListIsMutable();
        bufferPropInfoList_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllBufferPropInfoList(
          java.lang.Iterable<? extends message.S3PropInfo.PropInfo> values) {
        ensureBufferPropInfoListIsMutable();
        super.addAll(values, bufferPropInfoList_);
        
        return this;
      }
      public Builder clearBufferPropInfoList() {
        bufferPropInfoList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }
      public Builder removeBufferPropInfoList(int index) {
        ensureBufferPropInfoListIsMutable();
        bufferPropInfoList_.remove(index);
        
        return this;
      }
      
      // repeated .message.PropInfo effectPropInfoList = 3;
      private java.util.List<message.S3PropInfo.PropInfo> effectPropInfoList_ =
        java.util.Collections.emptyList();
      private void ensureEffectPropInfoListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          effectPropInfoList_ = new java.util.ArrayList<message.S3PropInfo.PropInfo>(effectPropInfoList_);
          bitField0_ |= 0x00000004;
         }
      }
      
      public java.util.List<message.S3PropInfo.PropInfo> getEffectPropInfoListList() {
        return java.util.Collections.unmodifiableList(effectPropInfoList_);
      }
      public int getEffectPropInfoListCount() {
        return effectPropInfoList_.size();
      }
      public message.S3PropInfo.PropInfo getEffectPropInfoList(int index) {
        return effectPropInfoList_.get(index);
      }
      public Builder setEffectPropInfoList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEffectPropInfoListIsMutable();
        effectPropInfoList_.set(index, value);
        
        return this;
      }
      public Builder setEffectPropInfoList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureEffectPropInfoListIsMutable();
        effectPropInfoList_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addEffectPropInfoList(message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEffectPropInfoListIsMutable();
        effectPropInfoList_.add(value);
        
        return this;
      }
      public Builder addEffectPropInfoList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEffectPropInfoListIsMutable();
        effectPropInfoList_.add(index, value);
        
        return this;
      }
      public Builder addEffectPropInfoList(
          message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureEffectPropInfoListIsMutable();
        effectPropInfoList_.add(builderForValue.build());
        
        return this;
      }
      public Builder addEffectPropInfoList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureEffectPropInfoListIsMutable();
        effectPropInfoList_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllEffectPropInfoList(
          java.lang.Iterable<? extends message.S3PropInfo.PropInfo> values) {
        ensureEffectPropInfoListIsMutable();
        super.addAll(values, effectPropInfoList_);
        
        return this;
      }
      public Builder clearEffectPropInfoList() {
        effectPropInfoList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      public Builder removeEffectPropInfoList(int index) {
        ensureEffectPropInfoListIsMutable();
        effectPropInfoList_.remove(index);
        
        return this;
      }
      
      // repeated .message.PropInfo lockPropInfoList = 4;
      private java.util.List<message.S3PropInfo.PropInfo> lockPropInfoList_ =
        java.util.Collections.emptyList();
      private void ensureLockPropInfoListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          lockPropInfoList_ = new java.util.ArrayList<message.S3PropInfo.PropInfo>(lockPropInfoList_);
          bitField0_ |= 0x00000008;
         }
      }
      
      public java.util.List<message.S3PropInfo.PropInfo> getLockPropInfoListList() {
        return java.util.Collections.unmodifiableList(lockPropInfoList_);
      }
      public int getLockPropInfoListCount() {
        return lockPropInfoList_.size();
      }
      public message.S3PropInfo.PropInfo getLockPropInfoList(int index) {
        return lockPropInfoList_.get(index);
      }
      public Builder setLockPropInfoList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLockPropInfoListIsMutable();
        lockPropInfoList_.set(index, value);
        
        return this;
      }
      public Builder setLockPropInfoList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureLockPropInfoListIsMutable();
        lockPropInfoList_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addLockPropInfoList(message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLockPropInfoListIsMutable();
        lockPropInfoList_.add(value);
        
        return this;
      }
      public Builder addLockPropInfoList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLockPropInfoListIsMutable();
        lockPropInfoList_.add(index, value);
        
        return this;
      }
      public Builder addLockPropInfoList(
          message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureLockPropInfoListIsMutable();
        lockPropInfoList_.add(builderForValue.build());
        
        return this;
      }
      public Builder addLockPropInfoList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureLockPropInfoListIsMutable();
        lockPropInfoList_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllLockPropInfoList(
          java.lang.Iterable<? extends message.S3PropInfo.PropInfo> values) {
        ensureLockPropInfoListIsMutable();
        super.addAll(values, lockPropInfoList_);
        
        return this;
      }
      public Builder clearLockPropInfoList() {
        lockPropInfoList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        
        return this;
      }
      public Builder removeLockPropInfoList(int index) {
        ensureLockPropInfoListIsMutable();
        lockPropInfoList_.remove(index);
        
        return this;
      }
      
      // repeated .message.BuyGold buyGoldList = 5;
      private java.util.List<message.S3BuyGold.BuyGold> buyGoldList_ =
        java.util.Collections.emptyList();
      private void ensureBuyGoldListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          buyGoldList_ = new java.util.ArrayList<message.S3BuyGold.BuyGold>(buyGoldList_);
          bitField0_ |= 0x00000010;
         }
      }
      
      public java.util.List<message.S3BuyGold.BuyGold> getBuyGoldListList() {
        return java.util.Collections.unmodifiableList(buyGoldList_);
      }
      public int getBuyGoldListCount() {
        return buyGoldList_.size();
      }
      public message.S3BuyGold.BuyGold getBuyGoldList(int index) {
        return buyGoldList_.get(index);
      }
      public Builder setBuyGoldList(
          int index, message.S3BuyGold.BuyGold value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuyGoldListIsMutable();
        buyGoldList_.set(index, value);
        
        return this;
      }
      public Builder setBuyGoldList(
          int index, message.S3BuyGold.BuyGold.Builder builderForValue) {
        ensureBuyGoldListIsMutable();
        buyGoldList_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addBuyGoldList(message.S3BuyGold.BuyGold value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuyGoldListIsMutable();
        buyGoldList_.add(value);
        
        return this;
      }
      public Builder addBuyGoldList(
          int index, message.S3BuyGold.BuyGold value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBuyGoldListIsMutable();
        buyGoldList_.add(index, value);
        
        return this;
      }
      public Builder addBuyGoldList(
          message.S3BuyGold.BuyGold.Builder builderForValue) {
        ensureBuyGoldListIsMutable();
        buyGoldList_.add(builderForValue.build());
        
        return this;
      }
      public Builder addBuyGoldList(
          int index, message.S3BuyGold.BuyGold.Builder builderForValue) {
        ensureBuyGoldListIsMutable();
        buyGoldList_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllBuyGoldList(
          java.lang.Iterable<? extends message.S3BuyGold.BuyGold> values) {
        ensureBuyGoldListIsMutable();
        super.addAll(values, buyGoldList_);
        
        return this;
      }
      public Builder clearBuyGoldList() {
        buyGoldList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        
        return this;
      }
      public Builder removeBuyGoldList(int index) {
        ensureBuyGoldListIsMutable();
        buyGoldList_.remove(index);
        
        return this;
      }
      
      // repeated .message.PropInfo headList = 6;
      private java.util.List<message.S3PropInfo.PropInfo> headList_ =
        java.util.Collections.emptyList();
      private void ensureHeadListIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          headList_ = new java.util.ArrayList<message.S3PropInfo.PropInfo>(headList_);
          bitField0_ |= 0x00000020;
         }
      }
      
      public java.util.List<message.S3PropInfo.PropInfo> getHeadListList() {
        return java.util.Collections.unmodifiableList(headList_);
      }
      public int getHeadListCount() {
        return headList_.size();
      }
      public message.S3PropInfo.PropInfo getHeadList(int index) {
        return headList_.get(index);
      }
      public Builder setHeadList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadListIsMutable();
        headList_.set(index, value);
        
        return this;
      }
      public Builder setHeadList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureHeadListIsMutable();
        headList_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addHeadList(message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadListIsMutable();
        headList_.add(value);
        
        return this;
      }
      public Builder addHeadList(
          int index, message.S3PropInfo.PropInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadListIsMutable();
        headList_.add(index, value);
        
        return this;
      }
      public Builder addHeadList(
          message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureHeadListIsMutable();
        headList_.add(builderForValue.build());
        
        return this;
      }
      public Builder addHeadList(
          int index, message.S3PropInfo.PropInfo.Builder builderForValue) {
        ensureHeadListIsMutable();
        headList_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllHeadList(
          java.lang.Iterable<? extends message.S3PropInfo.PropInfo> values) {
        ensureHeadListIsMutable();
        super.addAll(values, headList_);
        
        return this;
      }
      public Builder clearHeadList() {
        headList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        
        return this;
      }
      public Builder removeHeadList(int index) {
        ensureHeadListIsMutable();
        headList_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:message.PropInfoData)
    }
    
    static {
      defaultInstance = new PropInfoData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:message.PropInfoData)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
