// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KickOutDungoen.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "KickOutDungoen.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace message {

void protobuf_ShutdownFile_KickOutDungoen_2eproto() {
  delete NotifyKickedOutDungoen::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_KickOutDungoen_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_KickOutDungoen_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  NotifyKickedOutDungoen::default_instance_ = new NotifyKickedOutDungoen();
  NotifyKickedOutDungoen::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_KickOutDungoen_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_KickOutDungoen_2eproto_once_);
void protobuf_AddDesc_KickOutDungoen_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_KickOutDungoen_2eproto_once_,
                 &protobuf_AddDesc_KickOutDungoen_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_KickOutDungoen_2eproto {
  StaticDescriptorInitializer_KickOutDungoen_2eproto() {
    protobuf_AddDesc_KickOutDungoen_2eproto();
  }
} static_descriptor_initializer_KickOutDungoen_2eproto_;
#endif

// ===================================================================

bool NotifyKickedOutDungoen_KickedOutCause_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const NotifyKickedOutDungoen_KickedOutCause NotifyKickedOutDungoen::Gold_Coin_Shortage;
const NotifyKickedOutDungoen_KickedOutCause NotifyKickedOutDungoen::Time_Out;
const NotifyKickedOutDungoen_KickedOutCause NotifyKickedOutDungoen::Strength_Not_Enough;
const NotifyKickedOutDungoen_KickedOutCause NotifyKickedOutDungoen::KickedOutCause_MIN;
const NotifyKickedOutDungoen_KickedOutCause NotifyKickedOutDungoen::KickedOutCause_MAX;
const int NotifyKickedOutDungoen::KickedOutCause_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int NotifyKickedOutDungoen::kDidFieldNumber;
const int NotifyKickedOutDungoen::kCauseFieldNumber;
#endif  // !_MSC_VER

NotifyKickedOutDungoen::NotifyKickedOutDungoen()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void NotifyKickedOutDungoen::InitAsDefaultInstance() {
}

NotifyKickedOutDungoen::NotifyKickedOutDungoen(const NotifyKickedOutDungoen& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void NotifyKickedOutDungoen::SharedCtor() {
  _cached_size_ = 0;
  did_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  cause_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NotifyKickedOutDungoen::~NotifyKickedOutDungoen() {
  SharedDtor();
}

void NotifyKickedOutDungoen::SharedDtor() {
  if (did_ != &::google::protobuf::internal::kEmptyString) {
    delete did_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void NotifyKickedOutDungoen::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const NotifyKickedOutDungoen& NotifyKickedOutDungoen::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_KickOutDungoen_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_KickOutDungoen_2eproto();
#endif
  return *default_instance_;
}

NotifyKickedOutDungoen* NotifyKickedOutDungoen::default_instance_ = NULL;

NotifyKickedOutDungoen* NotifyKickedOutDungoen::New() const {
  return new NotifyKickedOutDungoen;
}

void NotifyKickedOutDungoen::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_did()) {
      if (did_ != &::google::protobuf::internal::kEmptyString) {
        did_->clear();
      }
    }
    cause_ = 1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool NotifyKickedOutDungoen::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string did = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_did()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_cause;
        break;
      }

      // optional .message.NotifyKickedOutDungoen.KickedOutCause cause = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_cause:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::message::NotifyKickedOutDungoen_KickedOutCause_IsValid(value)) {
            set_cause(static_cast< ::message::NotifyKickedOutDungoen_KickedOutCause >(value));
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void NotifyKickedOutDungoen::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string did = 1;
  if (has_did()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->did(), output);
  }

  // optional .message.NotifyKickedOutDungoen.KickedOutCause cause = 2;
  if (has_cause()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->cause(), output);
  }

}

int NotifyKickedOutDungoen::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string did = 1;
    if (has_did()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->did());
    }

    // optional .message.NotifyKickedOutDungoen.KickedOutCause cause = 2;
    if (has_cause()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->cause());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NotifyKickedOutDungoen::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const NotifyKickedOutDungoen*>(&from));
}

void NotifyKickedOutDungoen::MergeFrom(const NotifyKickedOutDungoen& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_did()) {
      set_did(from.did());
    }
    if (from.has_cause()) {
      set_cause(from.cause());
    }
  }
}

void NotifyKickedOutDungoen::CopyFrom(const NotifyKickedOutDungoen& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NotifyKickedOutDungoen::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void NotifyKickedOutDungoen::Swap(NotifyKickedOutDungoen* other) {
  if (other != this) {
    std::swap(did_, other->did_);
    std::swap(cause_, other->cause_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string NotifyKickedOutDungoen::GetTypeName() const {
  return "message.NotifyKickedOutDungoen";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)
